Repository KB-KkaBi/KkaBi-Frontend, pull requests merged in 2023-05, with the labels that each got.

#4 Chore - husky setting
  .husky/commit-msg
  commitlint.config.cjs
  package.json
  tsconfig.json
  yarn.lock
Labels: chore, ready

#6 Feat#1 common/settings
  .eslintrc.cjs
  .prettierrc
  index.html
  package.json
  public/kkabi.png
  public/vite.svg
  src/@components/.keep
  src/@pages/.keep
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/api/.keep
  src/core/.keep
  src/index.css
  src/main.tsx
  src/recoil/.keep
  src/style/globalStyle.tsx
  src/style/style.d.ts
  src/style/theme.tsx
  src/type/.keep
  src/utils/.keep
  yarn.lock
Labels: enhancement

#8 feat: route 기본 설정 추가
  package.json
  src/Router.tsx
  src/pages/Bank.tsx
  src/pages/Home.tsx
  src/pages/Invest.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/index.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement, ready

#14 Feat#11 common/layout
  src/@components/common/icon/Icons.tsx
  src/@components/common/iconButton/IconButton.tsx
  src/@components/common/iconButton/style.ts
  src/@components/common/index.ts
  src/@components/common/layout/CommonPaperLayout.tsx
  src/@components/common/layout/style.ts
  src/@pages/Landing.tsx
  src/assets/icons/arrow-back.svg
  src/assets/vector-6.png
  src/assets/vector-9.png
Labels: feature

#15 Feat#10 home/layout
  package.json
  src/@components/Home/MyInfo.tsx
  src/@components/Home/style.tsx
  src/@pages/Home.tsx
  src/assets/assets.d.ts
  src/assets/icon/bigprofileAgo.svg
  src/assets/icon/bigprofileBB.svg
  src/assets/icon/bigprofileKiki.svg
  src/assets/icon/bigprofileKolly.svg
  src/assets/icon/bigprofileLamu.svg
  src/assets/icon/characterAgo.svg
  src/assets/icon/characterBb.svg
  src/assets/icon/characterKiki.svg
  src/assets/icon/characterKolly.svg
  src/assets/icon/characterLamu.svg
  src/assets/icon/homeKkaBiBankIc.svg
  src/assets/icon/homeMyInfoIc.svg
  src/assets/icon/homeTreasureIc.svg
  src/assets/icon/miniprofileAgo.svg
  src/assets/icon/miniprofileBB.svg
  src/assets/icon/miniprofileKiki.svg
  src/assets/icon/miniprofileKolly.svg
  src/assets/icon/miniprofileLamu.svg
  src/assets/icon/rank1.svg
  src/assets/icon/rank2.svg
  src/assets/icon/rank3.svg
  src/assets/icon/rank4.svg
  src/assets/icon/rank5.svg
  src/assets/icon/rank6.svg
  src/assets/image/homeBackground.png
  src/assets/index.ts
  src/assets/react.svg
  src/core/.keep
  src/core/starFriends.tsx
  vite.config.ts
  yarn.lock
Labels: ui, feature

#21 Feat#20 myAccount/view
  src/@components/common/index.ts
  src/@components/common/input/style.ts
  src/@components/common/layout/CommonBankLayout.tsx
  src/@components/common/layout/CommonPaperLayout.tsx
  src/@components/common/layout/style.ts
  src/@pages/Bank.tsx
  src/@pages/MyAccount/AccountLog.tsx
  src/@pages/MyAccount/Deposit.tsx
  src/@pages/MyAccount/LogDetailContainer.tsx
  src/@pages/MyAccount/MyAccountMain.tsx
  src/@pages/MyAccount/Router.tsx
  src/@pages/MyAccount/Withdraw.tsx
  src/@pages/MyAccount/index.ts
  src/@pages/MyAccount/style.tsx
  src/@pages/index.tsx
  src/Router.tsx
  src/assets/image/bank_main.png
  src/assets/image/vector-6.png
  src/assets/image/vector-9.png
Labels: feature

#28 Refactor#19 home/layout
  src/@components/Home/Character/Character.tsx
  src/@components/Home/Character/style.tsx
  src/@components/Home/MyInfo/MyInfo.tsx
  src/@components/Home/MyInfo/style.tsx
  src/@pages/Home.tsx
  src/assets/icon/bigprofileAgo.svg
  src/assets/icon/bigprofileBB.svg
  src/assets/icon/bigprofileKiki.svg
  src/assets/icon/bigprofileKolly.svg
  src/assets/icon/bigprofileLamu.svg
  src/assets/icon/characterAgo.svg
  src/assets/icon/characterBb.svg
  src/assets/icon/characterKiki.svg
  src/assets/icon/characterKolly.svg
  src/assets/icon/characterLamu.svg
  src/assets/icon/miniprofileBB.svg
  src/assets/icon/miniprofileKiki.svg
  src/assets/icon/miniprofileKolly.svg
  src/assets/icon/miniprofileLamu.svg
Labels: design, refactor

#55 Style#54 quiz/route
  src/@pages/Invest.tsx
  src/@pages/index.tsx
  src/@pages/invest/Router.tsx
  src/@pages/invest/SelectTreasure.tsx
  src/@pages/invest/SelectTreasureCnt.tsx
  src/@pages/invest/TreasureCard.tsx
  src/@pages/invest/TreasureCardContent.tsx
  src/@pages/invest/index.ts
  src/@pages/invest/quiz/AnswerButton.tsx
  src/@pages/invest/quiz/AnswerSelector.tsx
  src/@pages/invest/quiz/Quiz.tsx
  src/@pages/invest/quiz/style.tsx
  src/@pages/invest/style.tsx
  src/@pages/treasure/Router.tsx
  src/Router.tsx
Labels: ready, feature

#59 Feat#48 banks/getaccountlist
  src/@pages/bank/selectAccount/AccountCard.tsx
  src/@pages/bank/selectAccount/AccountCardContent.tsx
  src/@pages/bank/selectAccount/CreateNewAccount.tsx
  src/@pages/bank/selectAccount/CreateNewAccountName.tsx
  src/@pages/bank/selectAccount/SelectMyAccount.tsx
  src/@pages/bank/selectAccount/style.tsx
  src/api/account.tsx
  src/core/accountsData.tsx
  src/core/myAccountData.tsx
  vite.config.ts
Labels: feature, account

#62 Feat#45 treasure/account list get
  src/@components/common/card/Card.tsx
  src/@pages/.keep
  src/@pages/Home.tsx
  src/@pages/Login/Login.tsx
  src/@pages/bank/selectAccount/SelectMyAccount.tsx
  src/@pages/invest/Router.tsx
  src/@pages/invest/SelectMyAccount.tsx
  src/@pages/invest/SelectTreasure.tsx
  src/@pages/invest/SelectTreasureCnt.tsx
  src/@pages/invest/TreasureCard.tsx
  src/@pages/invest/index.ts
  src/@pages/invest/quiz/Quiz.tsx
  src/api/account.tsx
  src/api/register.tsx
  src/api/treasure.tsx
  src/recoil/Invest.tsx
  vite.config.ts
Labels: feature, design

#84 Feat#76 accountlog/insertaccountlog
  src/@pages/bank/MyAccountMain.tsx
  src/@pages/bank/accountTransaction/Deposit.tsx
  src/@pages/bank/accountTransaction/Withdraw.tsx
  src/@pages/bank/selectAccount/SelectMyAccount.tsx
  src/@pages/invest/SelectMyAccount.tsx
  src/@pages/invest/SelectTreasureCnt.tsx
  src/api/account.tsx
  src/api/register.tsx
  src/recoil/bank.tsx
Labels: feature, account

#85 Feat#81 account/get account log
  src/@pages/bank/accountLog/AccountLog.tsx
  src/@pages/bank/accountLog/LogDetailContainer.tsx
  src/@pages/bank/accountLog/style.ts
  src/api/accountLog.tsx
  src/assets/icon/leftArrow.svg
  src/assets/icon/rightArrow.svg
  src/assets/index.ts
  src/recoil/bank.tsx
  src/style/theme.tsx
Labels: feature

#93 Hotfix#92 common/error
  src/@components/Home/MyInfo/MyInfo.tsx
  src/@components/Home/MyInfo/style.tsx
  src/@pages/bank/selectAccount/SelectMyAccount.tsx
  src/assets/icon/HomeBankActiveIc.svg
  src/assets/icon/HomeTreasureActiveIc.svg
  src/recoil/load.tsx
Labels: fix

#111 Feat#110 account/detail
  src/@components/common/layout/CommonBankLayout.tsx
  src/@pages/Home.tsx
  src/@pages/Landing.tsx
  src/@pages/bank/BankMain.tsx
  src/@pages/bank/MyAccountMain.tsx
  src/@pages/bank/accountLog/AccountLog.tsx
  src/@pages/bank/accountTransaction/Deposit.tsx
  src/@pages/bank/accountTransaction/Withdraw.tsx
  src/@pages/bank/selectAccount/CreateNewAccount.tsx
  src/@pages/bank/selectAccount/SelectMyAccount.tsx
  src/api/account.tsx
  src/recoil/bank.tsx
Labels: fix

#117 Hotfix#116 common/qa
  src/@pages/MyPage/QuizNote.tsx
  src/@pages/MyPage/styles/mypageStyle.ts
  src/@pages/bank/MyAccountMain.tsx
  src/@pages/invest/quiz/Quiz.tsx
  src/api/mypage.tsx
Labels: fix
